config/routes.rb
Rails.application.routes.draw do
 

 resources :pins

 root "pages#home"

 get "documentos" => "pages#documentos"
 get "enlaces" => "pages#enlaces"
 get "investigadores" => "pages#investigadores"
 get "calendario" => "pages#calendario"
 get "discusion" => "pins#new"
 get "galeria" => "pages#galeria" 

 match 'contact' => 'contact#new', :as => 'getcontact', :via => :get
 match 'contact' => 'contact#create', :as => 'postcontact', :via => :post

end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/pin.rb
class Pin < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      Notificationsmailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def investigadores
  end

  def enlaces
  end

  def documentos
  end

  def calendario
  end

  def discusion
  end

  def galeria
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  def index
    @pins = Pin.all
  end

  def show
  end

  def new
    @pin = Pin.new
  end

  def edit
  end

  def create
    @pin = Pin.new(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/contact/new.html.erb
<%= form_for @message, :url => getcontact_path do |form| %>
  
<div class="row">
  <div class="col-xs-6" style="margin-left:2%"> 


   <form role="form">
  
    <div class="form-group" style="margin-top:2%">
      <label> <%= form.label :nombre %> </label>
     <input class="form-control" id="message_name" name="message[name]" type="text"> 
    </div>

    
    <div class="form-group">
        <label> <%= form.label :correo_electrónico %> </label>
        <input class="form-control" id="message_email" name="message[email]" type="text">
    </div>

    <div class="form-group">
        <label> <%= form.label :asunto %> </label>
       <input class="form-control" id="message_subject" name="message[subject]" type="text">
     </div>
    
    <div class="form-group">
        <label> <%= form.label :comentarios %> </label>
        <textarea class="form-control" id="message_body" name="message[body]" type="text" rows="4"> </textarea>
    </div>


  <button type="submit" class="btn btn-default">  Enviar </button>

</form>

</div>

  <div class="col-xs-6"></div>
</div>
 

<% end %>

app/views/layouts/_campo1.html.erb
<div id="carousel-campo1" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-campo1" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-campo1" data-slide-to="1"></li>
    <li data-target="#carousel-campo1" data-slide-to="2"></li>
    <li data-target="#carousel-campo1" data-slide-to="3"></li>
    <li data-target="#carousel-campo1" data-slide-to="4"></li>
    <li data-target="#carousel-campo1" data-slide-to="5"></li>
    <li data-target="#carousel-campo1" data-slide-to="6"></li>
    <li data-target="#carousel-campo1" data-slide-to="7"></li>
      </ol>


  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    
    <div class="item active peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/10_1_14_-_%2317_finca_arroz_guanica.jpg"alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
    
    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/10_1_14-_%2316_estancamiento.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
    
    <div class="item peopleCarousel">
      <img ="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/10_22_14-%2310_deslizamiento.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
  

    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/10_22_14-%2310_pared_con_marca_de_agua.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
    
    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/10_22_14-%2315_puente.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>

    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/10_22_14-%236_casas_y_grava.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
    
    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/10_22_14-tributario_a_la_%2310.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption"></div>
    </div>

    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/10_8_14-%2319__descarga_a_bahia_cmp.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption"> </div>
    </div>
    
  
    
  </div>




  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-campo1" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span></a>
  <a class="right carousel-control" href="#carousel-campo1" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span></a>

</div>

app/views/layouts/_campo2.html.erb
<div id="carousel-campo2" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
   <ol class="carousel-indicators">
    <li data-target="#carousel-campo2" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-campo2" data-slide-to="1"></li>
    <li data-target="#carousel-campo2" data-slide-to="2"></li>
    <li data-target="#carousel-campo2" data-slide-to="3"></li>
    <li data-target="#carousel-campo2" data-slide-to="4"></li>
    <li data-target="#carousel-campo2" data-slide-to="5"></li>
    <li data-target="#carousel-campo2" data-slide-to="6"></li>
    <li data-target="#carousel-campo2" data-slide-to="7"></li>
    <li data-target="#carousel-campo2" data-slide-to="8"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    
    <div class="item active peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/10_8_14-%2320_paisaje_y_tubo_descarga_cmpr.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
    
    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/20140609_134523.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
    
    <div class="item peopleCarousel">
      <img ="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/10_22_14-%2310_deslizamiento.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
  

    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/20140803_173054.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
    
    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/20140609_134554.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>

    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/20140803_173109.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
    
    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/20140805_074842.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption"></div>
    </div>

    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/20140806_120521.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption"> </div>
    </div>
    
    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/20140806_130055.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption"></div>
    </div>
    
  </div>




  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-campo2" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span></a>
  <a class="right carousel-control" href="#carousel-campo2" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span></a>

</div>

app/views/layouts/_campo3.html.erb
<div id="carousel-campo3" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
   <ol class="carousel-indicators">
    <li data-target="#carousel-campo3" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-campo3" data-slide-to="1"></li>
    <li data-target="#carousel-campo3" data-slide-to="2"></li>
    <li data-target="#carousel-campo3" data-slide-to="3"></li>
    <li data-target="#carousel-campo3" data-slide-to="4"></li>
    <li data-target="#carousel-campo3" data-slide-to="5"></li>
    <li data-target="#carousel-campo3" data-slide-to="6"></li>
  </ol>
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    
    <div class="item active peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/20140806_130104.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
    
    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/20140806_132404.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
    
    <div class="item peopleCarousel">
      <img ="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/20140806_132413.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
  

    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/20140803_173054.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
    
    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/20140806_132434.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>

    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/canal-drenaje-valle-lajas_1.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
    
    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/canalderiego.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption"></div>
    </div>
    
  </div>




  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-campo3" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span></a>
  <a class="right carousel-control" href="#carousel-campo3" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span></a>

</div>

app/views/layouts/_club4h.html.erb
<div id="carousel-club4h" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
   <ol class="carousel-indicators">
    <li data-target="#carousel-club4h" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-club4h" data-slide-to="1"></li>
    <li data-target="#carousel-club4h" data-slide-to="2"></li>
    <li data-target="#carousel-club4h"data-slide-to="3"></li>
    <li data-target="#carousel-club4h" data-slide-to="4"></li>
    <li data-target="#carousel-club4h" data-slide-to="5"></li>
  </ol>
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    
    <div class="item active peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/club4h/20140806_084252.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
    
    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/club4h/014.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
    
    <div class="item peopleCarousel">
      <img ="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/club4h/018.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
  

    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/club4h/028.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
    
    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/club4h/068.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>

    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/club4h/dsc01431.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">  </div>
    </div>
    
  </div>




  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-club4h" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span></a>
  <a class="right carousel-control" href="#carousel-club4h" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span></a>

</div>

app/views/layouts/_footer.html.erb
<div class="push"> </div>
<div class="footer">
<div class="jumbotron" id="footerJumbotron">
  		<div class="container">
        <div class="row">

          <div class="col-xs-6">
            <img src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/logos/uprm2.png" width="100px" height="100px" style="margin-left:5%"/>
            <img src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/logos/estacion_agricola_burned.png" width="100px" height="100px" style="margin-left:2%"/>
          </div>

          <div class="col-xs-6">  
            <p style="font-size:14px"> 
              <strong> Recinto Universitario de Mayagüez </strong> <br>
              Universidad de Puerto Rico <br>
              Mayagüez PR 00681-9000 <br>
              Tel: (787) 832-4040 <br>
              <strong> <%= link_to "Contáctanos", getcontact_path %> </strong>
            </p>
          </div>

        </div>
	 </div>
  </div>
</div>

         


 

  

      

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation" style="margin-bottom:0">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"> Avaluo de la Calidad de Agua en el Suroeste de Puerto Rico</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Personal", investigadores_path %></li> 
      <li><%= link_to "Documentos", documentos_path %></li>
      <li><%=link_to "Galería", galeria_path %></li>
      <li><%= link_to "Enlaces", enlaces_path %></li> 
      <li><%= link_to "Discusión", pins_path %></li>
      <li><%= link_to "Calendario", calendario_path %></li> 
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Waterqualitypr</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render 'layouts/header' %> 
	<div class="container" id="myContainer">
		<%= yield %>
	</div>
</body>
<%= render 'layouts/footer' %> 

</html>

app/views/pages/home.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/10_8_14-%2320_paisaje_y_tubo_descarga_cmpr.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">
        Punto de muestreo en la bahía de Guanica
      </div>
    </div>
    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/muestreo/sampling_points.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">
        Estaciones de muestreo     
      </div>
    </div>
    <div class="item peopleCarousel">
      <img class="peopleCarousel" src="https://s3-us-west-2.amazonaws.com/waterqualitypr/images/campo/canalderiego.jpg" alt="...">
      <div class="carousel-caption" id="myCarouselCaption">
        Canal de riego en Lajas
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
</div>


<div class="row">
  <div class="col-xs-4" id="homeColumns" style="margin-top:30px"> <h3> Bienvenidos a nuestro portal del proyecto: </h3> 
  <strong>Avalúo de la Calidad del Agua y de la Infraestructura de Tratamiento de Aguas en el Suroeste de Puerto Rico.
  </strong>
  <br></br>
  Este proyecto se realiza como un proyecto colaborativo entre la Universidad de Puerto Rico, Recinto de Mayagüez, Colegio de Ciencias Agrícolas (UPR-RUM) y la Agencia de Protección Ambiental (US EPA por sus siglas en inglés), Gulf Ecology Division, Gulf Breeze, Fl. 
<br></br>
  El objetivo del portal es tener un foro de presentación del proyecto, y que sirva de plataforma educativa e interactiva para que los participantes puedan conocer sobre todo los aspectos del proyecto y sobre el tema de calidad de aguas y fuentes de contaminación fecal en el Suroeste de Puerto Rico. 
<br></br> 
  Hemos optado por operar este portal en el idioma español para facilitar la participación e interacción de los participantes voluntarios y del público en general que quiera interactuar. 
</div>
  
  <div class="col-xs-4" id="homeColumns" style="margin-top:52px"> 
  Esperamos que a través de la ejecución del proyecto, de la participación de los estudiantes, y de la diseminación de los resultados, se cree mayor conciencia sobre la importancia del mantenimiento de la calidad de agua en Puerto Rico. En particular nos interesa que el público conozca sobre la importancia del buen uso de las tierras y como los distintos usuarios en una cuenca pueden contribuir al mantenimiento de la calidad de las aguas minimizando la contaminación fecal.
<br></br>
En este proyecto participan investigadores del UPR-RUM, investigadores de la USEPA, estudiantes graduados, estudiantes subgraduados y personal de apoyo técnico de UPR-RUM y estudiantes participantes de programas 4-H del Servicio de Extensión Agrícola.
<br></br>
  Si tienes preguntas específicas sobre la calidad de aguas en tu área, trataremos de orientarte en la dirección correcta con las personas adecuadas. Nos puedes <%= link_to "contactar", getcontact_path %> o escribir en nuestro blog interactivo. 
<br></br>

  <strong> David Sotomayor Ramírez, Ph.D. Coordinador del Proyecto </strong> 
  </div>
  
  <div class="col-xs-4" id="homeColumns" style="margin-top:52px"> 
<a class="twitter-timeline" href="https://twitter.com/waterqualitypr" data-widget-id="537255588930265088">Tweets by @waterqualitypr</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>
</div>

app/views/pins/edit.html.erb
<div class="jumbotron" id="myJumbotron">
  <div class="container" style="text-align:center">
    <h3> Edita tu árticulo </h3>
  </div>
</div>

<%= render 'form' %> 

<div style="margin-left:2%">
<%= link_to 'Ver árticulo', @pin %> | <%= link_to 'Volver', pins_path %> 
</div>

app/views/pins/index.html.erb
<div class="jumbotron" id="myJumbotron">
  <div class="container" style="text-align:center">
    <h3> Lista de artículos </h3>
  </div>
</div>

<br> </br> 



<table class="table table-striped" id="indexPinsTable">
<tr> 
  <th> Descripción </th>
  <th> Acción </th>
</tr>
  <% @pins.each do |pin| %>
  <tr> 
    <td> <%= pin.description %> </td>
    <td> <%=link_to 'Ver', pin %> | Editar | Borrar </td>
  </tr>
  <% end %>
</table>

<button type="button" class="btn btn-default" id="indexPinsBtn"> <%= link_to 'Añadir Árticulo', new_pin_path %>  </button> 

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="panel panel-default" id="showPinsPanel">
  <div class="panel-heading">
    <h3 class="panel-title"> <%= @pin.description %> </h3>
  </div>
  <div class="panel-body">
    <%= @pin.body %> 
    <br></br>
  <%= link_to 'Editar', edit_pin_path(@pin) %> |
  <%= link_to 'Volver', pins_path %>
  </div>

</div>

<div style="margin-left: 2%; margin-right:2%">

  <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'waterqualitypr'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

</div>